import { Type } from 'class-transformer';
import { ArrayMaxSize, IsArray, IsBoolean, IsInt, IsNumber, IsOptional, IsString, Length, Matches, Min, ValidateNested } from 'class-validator';

const ISO_DATE = /^\d{4}-\d{2}-\d{2}$/;

export class StagePlanItemDto {
  @IsString() @Length(1, 40) key!: string;
  @IsOptional() @Matches(ISO_DATE) plannedFrom?: string;
  @IsOptional() @Matches(ISO_DATE) plannedTo?: string;
}

export class CreateTenderDto {
  @IsString() @Length(1, 200) titleAr!: string;
  @IsString() @Length(1, 200) titleEn!: string;
  @IsString() @Length(1, 40) budgetCode!: string;
  @IsString() @Length(1, 64) fieldId!: string; // the oil field this request belongs to (§1); FA derives from its contract
  @IsNumber() @Min(0) estimatedValueUSD!: number;
  /** §9 work scope — drives the C8.1/C8.2 state-company requirement with above-authority */
  @IsOptional() @Matches(/^(DRILLING|ENGINEERING_CONSTRUCTION|HEAVY_MATERIALS|OTHER)$/) scope?: string;

  @IsOptional() @IsBoolean() specializedOrEmergency?: boolean;
  @IsOptional() @IsBoolean() technicallyComplex?: boolean;
  @IsOptional() @IsBoolean() hasPreQualifiedList?: boolean;
  @IsOptional() @IsBoolean() hasRecentQualifiedBidders?: boolean;
  @IsOptional() @Matches(/^[a-g]$/) soleSourceCase?: string;

  /** override the engine suggestion — requires a justification */
  @IsOptional() @IsInt() @Min(1) methodIdOverride?: number;
  @IsOptional() @IsString() overrideJustification?: string;

  /** optional planned dates per stage, generated by the request wizard */
  @IsOptional() @IsArray() @ArrayMaxSize(20) @ValidateNested({ each: true }) @Type(() => StagePlanItemDto)
  stagePlan?: StagePlanItemDto[];
}

export class SetPriceDto {
  @IsString() bidderId!: string;
  @IsNumber() @Min(0) priceUSD!: number;
}

export class CompleteStageDto {
  @IsString() stageKey!: string;
  @Matches(/^\d{4}-\d{2}-\d{2}$/) actualTo!: string;
  /** D1 — actual start recorded at closing; informational, deadlines still read actualTo */
  @IsOptional() @Matches(ISO_DATE) actualFrom?: string;
  /** D1 — classified deviation reason; the SAME closed vocabulary the client wizard offers
   *  (store DEV_REASON_CATS) and the same ≥15-char detail bound the wizard enforces */
  @IsOptional() @Matches(/^(publisherDelay|docsCompletion|forceMajeure|internalCoord)$/) devReasonCat?: string;
  @IsOptional() @IsString() @Length(15, 2000) devReasonNote?: string;
}

/** The immutable oid of the acting officer, sent by the client alongside governance
 *  calls. Accepted (whitelisted) but never trusted for attribution — the service
 *  persists the authenticated JWT principal, not this value. */
export class ActorRefDto {
  @IsOptional() @IsString() @Length(1, 64) byOid?: string;
}

/** Ratify carries no payload beyond the optional actor hint. */
export class RatifyDto extends ActorRefDto {}

export class ReturnDto extends ActorRefDto {
  @IsString() @Length(1, 1000) notes!: string;
}

export class PlanStageDto {
  @IsString() stageKey!: string;
  @IsOptional() @Matches(/^\d{4}-\d{2}-\d{2}$/) plannedFrom?: string;
  @IsOptional() @Matches(/^\d{4}-\d{2}-\d{2}$/) plannedTo?: string;
}

export class AnnouncementPatchDto {
  @IsOptional() @IsInt() @Min(0) periodDays?: number;
  @IsOptional() @IsString({ each: true }) newspapers?: string[];
  @IsOptional() @IsBoolean() lcWebsite?: boolean;
  @IsOptional() @IsBoolean() rocWebsite?: boolean;
  @IsOptional() @IsInt() @Min(0) inviteeCount?: number;
  @IsOptional() @IsBoolean() inviteesPreQualified?: boolean;
  @IsOptional() @Matches(/^(public|limited|direct)$/) mode?: string;
}

export class EvalStepDto {
  @IsInt() @Min(0) step!: number;
}

export class AddBidderDto {
  @IsString() @Length(1, 160) name!: string;
  /** link to a registry vendor — triggers the 10.4 eligibility gate */
  @IsOptional() @IsString() vendorId?: string;
  /** recorded submission date (YYYY-MM-DD) — triggers the 10.6.1 late-bid gate when present */
  @IsOptional() @Matches(ISO_DATE) submittedAt?: string;
}

export class SetTechnicalDto {
  @IsString() bidderId!: string;
  @Matches(/^(pass|fail)$/) result!: string;
}

/** §9 C8.1 — the operator's attestation that the tender documents carry the 20% participation
 *  clause. The attestation is a plain fact (affixed / not), so it carries no justification: what
 *  makes it governed is that it is the gate publication must pass, and that it is audited. */
export class LocalContentClauseDto extends ActorRefDto {
  @IsBoolean() affixed!: boolean;
}

/** §9 C8.2 — record a state company's response on a tender (governed: a documented reason ≥20). */
export class StateResponseDto {
  @IsString() @Length(1, 40) company!: string;
  @Matches(/^(accepted|pending|declined)$/) status!: string;
  @IsString() @Length(20, 2000) reason!: string;
}

/** §9 C8.6 — one bidder's origin declaration for one critical material. */
export class MaterialDeclarationDto {
  @IsString() @Length(1, 64) materialId!: string;
  @IsBoolean() imported!: boolean;
  @IsOptional() @IsString() @Length(0, 64) origin?: string;
  @IsOptional() @IsString() @Length(0, 64) oemAuthorizedFrom?: string;
  @IsOptional() @IsBoolean() onMooList?: boolean;
}

export class SetMaterialsDto {
  @IsArray() @ArrayMaxSize(64) @ValidateNested({ each: true }) @Type(() => MaterialDeclarationDto) materials!: MaterialDeclarationDto[];
}

export class ToggleDocDto {
  @IsString() stageKey!: string;
  @IsString() doc!: string;
}

/* ---- MCT cost cycle (6.9) ---- */

export class MctMeetingDto {
  @Matches(/^\d{4}-\d{2}-\d{2}$/) meetingHeldOn!: string;
}
export class MctAgreementDto {
  @Matches(/^\d{4}-\d{2}-\d{2}$/) agreementReachedOn!: string;
  @IsNumber() @Min(1) agreedEstimateUSD!: number;
}
export class MctEstimateDto {
  @IsNumber() @Min(1) mctEstimateUSD!: number;
}

/* ---- tender governance (cancel / suspend / resume) ---- */

export class TenderStatusChangeDto extends ActorRefDto {
  @IsString() @Length(20, 2000) justification!: string;
}
